### ISSUE TITLE
Tests not passing on Apple M1

### ISSUE THREAD

**Issue by joostjager** [bottlepay/lndsigner#35]
There seem to be multiple failures. Output below. Running 96f91e43c54694325df28d71eb8b2aeb0bb91c2c

```
~/bottle/lndsigner (integration-tests ✔) make docker-test-all
docker build -t lndsigner-builder:latest .
[+] Building 1.4s (8/8) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                      0.0s
 => => transferring dockerfile: 1.10kB                                                                                                                    0.0s
 => [internal] load .dockerignore                                                                                                                         0.0s
 => => transferring context: 2B                                                                                                                           0.0s
 => [internal] load metadata for docker.io/library/golang:1.19.5                                                                                          1.3s
 => [1/4] FROM docker.io/library/golang:1.19.5@sha256:09009d430dbf3fb80a4731546eefb1603f1fdb36fe6354eab138d8275a85e89f                                    0.0s
 => CACHED [2/4] RUN apt update && apt-get install -y zip                                                                                                 0.0s
 => CACHED [3/4] RUN cd /root &&     wget https://bitcoincore.org/bin/bitcoin-core-24.0.1/bitcoin-24.0.1-x86_64-linux-gnu.tar.gz &&     tar xfz bitcoin-  0.0s
 => CACHED [4/4] WORKDIR /app                                                                                                                             0.0s
 => exporting to image                                                                                                                                    0.0s
 => => exporting layers                                                                                                                                   0.0s
 => => writing image sha256:2d607f72928183eb5f18d4d4a98d0b8a7bbd122454642509e594d5e8d32e8f7d                                                              0.0s
 => => naming to docker.io/library/lndsigner-builder:latest                                                                                               0.0s

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
docker run -t --rm \
		--mount type=bind,source=/Users/joost.jager/bottle/lndsigner,target=/app lndsigner-builder:latest \
		make test-all
go install -race -buildvcs=false ./cmd/... && go test -v -count=1 -race -tags=itest -cover ./...
go: downloading github.com/hashicorp/vault/api v1.8.0
go: downloading github.com/hashicorp/go-hclog v1.3.1
go: downloading github.com/hashicorp/vault/sdk v0.6.0
go: downloading github.com/jessevdk/go-flags v1.4.0
go: downloading github.com/Yawning/aez v0.0.0-20211027044916-e49e68abd344
go: downloading github.com/btcsuite/btcd/btcec/v2 v2.2.1
go: downloading github.com/btcsuite/btcd v0.23.1
go: downloading github.com/btcsuite/btcd/btcutil v1.1.2
go: downloading github.com/kkdai/bstream v0.0.0-20161212061736-f391b8402d23
go: downloading golang.org/x/crypto v0.0.0-20220315160706-3147a52a75dd
go: downloading github.com/btcsuite/btcd/btcutil/psbt v1.1.5
go: downloading github.com/tv42/zbase32 v0.0.0-20160707012821-501572607d02
go: downloading go.uber.org/zap v1.23.0
go: downloading google.golang.org/grpc v1.47.0
go: downloading github.com/fatih/color v1.13.0
go: downloading github.com/mattn/go-isatty v0.0.14
go: downloading github.com/cenkalti/backoff/v3 v3.0.0
go: downloading github.com/hashicorp/errwrap v1.1.0
go: downloading github.com/hashicorp/go-cleanhttp v0.5.2
go: downloading github.com/hashicorp/go-multierror v1.1.1
go: downloading github.com/hashicorp/go-retryablehttp v0.6.6
go: downloading github.com/hashicorp/go-rootcerts v1.0.2
go: downloading github.com/hashicorp/go-secure-stdlib/parseutil v0.1.6
go: downloading github.com/hashicorp/hcl v1.0.0
go: downloading github.com/mitchellh/mapstructure v1.5.0
go: downloading golang.org/x/net v0.0.0-20220722155237-a158d28d115b
go: downloading golang.org/x/time v0.0.0-20200416051211-89c76fbcd5d1
go: downloading gopkg.in/square/go-jose.v2 v2.5.1
go: downloading github.com/hashicorp/go-plugin v1.4.5
go: downloading gitlab.com/yawning/bsaes.git v0.0.0-20190805113838-0a714cd429ec
go: downloading github.com/decred/dcrd/dcrec/secp256k1/v4 v4.0.1
go: downloading github.com/btcsuite/btcd/chaincfg/chainhash v1.0.1
go: downloading github.com/btcsuite/btclog v0.0.0-20170628155309-84c8d2346e9f
go: downloading github.com/evanphx/json-patch/v5 v5.5.0
go: downloading github.com/hashicorp/go-kms-wrapping/entropy/v2 v2.0.0
go: downloading github.com/hashicorp/go-secure-stdlib/strutil v0.1.2
go: downloading github.com/hashicorp/go-uuid v1.0.2
go: downloading github.com/mitchellh/copystructure v1.0.0
go: downloading github.com/hashicorp/go-sockaddr v1.0.2
go: downloading github.com/mitchellh/go-testing-interface v1.0.0
go: downloading google.golang.org/protobuf v1.28.0
go: downloading github.com/ryanuber/go-glob v1.0.0
go: downloading go.uber.org/multierr v1.6.0
go: downloading go.uber.org/atomic v1.9.0
go: downloading github.com/mattn/go-colorable v0.1.12
go: downloading golang.org/x/sys v0.0.0-20220722155257-8c9f86f7a55f
go: downloading github.com/golang/protobuf v1.5.2
go: downloading github.com/hashicorp/go-secure-stdlib/mlock v0.1.1
go: downloading github.com/hashicorp/go-version v1.2.0
go: downloading google.golang.org/genproto v0.0.0-20210924002016-3dee208752a0
go: downloading github.com/hashicorp/yamux v0.0.0-20180604194846-3520598351bb
go: downloading github.com/oklog/run v1.0.0
go: downloading github.com/golang/snappy v0.0.4
go: downloading github.com/pierrec/lz4 v2.5.2+incompatible
go: downloading github.com/armon/go-metrics v0.3.9
go: downloading github.com/armon/go-radix v1.0.0
go: downloading github.com/pkg/errors v0.9.1
go: downloading github.com/mitchellh/reflectwalk v1.0.0
go: downloading github.com/decred/dcrd/crypto/blake256 v1.0.0
go: downloading golang.org/x/text v0.3.7
go: downloading github.com/hashicorp/go-immutable-radix v1.3.1
go: downloading github.com/stretchr/testify v1.8.0
go: downloading github.com/benbjohnson/clock v1.1.0
go: downloading gopkg.in/yaml.v3 v3.0.1
go: downloading github.com/davecgh/go-spew v1.1.1
go: downloading github.com/pmezard/go-difflib v1.0.0
?   	github.com/bottlepay/lndsigner	[no test files]
?   	github.com/bottlepay/lndsigner/cmd/lndsignerd	[no test files]
?   	github.com/bottlepay/lndsigner/cmd/vault-plugin-lndsigner	[no test files]
=== RUN   TestIntegration
2023-02-08T07:30:04.106Z	WARN	WARNING: Service exited with error	{"cmd": "/usr/local/bin/bitcoind", "err": "exit status 255", "stdout/stderr": "qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory\n"}
github.com/bottlepay/lndsigner/itest_test.waitProc
	/app/itest/itest_lndharness_test.go:277
coverage: 6.7% of statements
panic: test timed out after 10m0s

goroutine 36 [running]:
testing.(*M).startAlarm.func1()
	/usr/local/go/src/testing/testing.go:2036 +0xb4
created by time.goFunc
	/usr/local/go/src/time/sleep.go:176 +0x48

goroutine 1 [chan receive]:
testing.(*T).Run(0xc0002191e0, {0x9b61d8, 0xf}, 0xac05c8)
	/usr/local/go/src/testing/testing.go:1494 +0x584
testing.runTests.func1(0x0?)
	/usr/local/go/src/testing/testing.go:1846 +0x94
testing.tRunner(0xc0002191e0, 0xc00014fb68)
	/usr/local/go/src/testing/testing.go:1446 +0x18c
testing.runTests(0xc00034c500?, {0x1067870, 0x1, 0x1}, {0xc000332d50?, 0x16f8f0?, 0x1081c40?})
	/usr/local/go/src/testing/testing.go:1844 +0x6d0
testing.(*M).Run(0xc00034c500)
	/usr/local/go/src/testing/testing.go:1726 +0x880
main.main()
	_testmain.go:99 +0x3bc

goroutine 34 [sleep]:
time.Sleep(0x5f5e100)
	/usr/local/go/src/runtime/time.go:195 +0x120
github.com/bottlepay/lndsigner/itest_test.waitFile(0xc0000afbc8?, {0xc0003f60c0, 0x37}, {0x9bf012, 0x1a})
	/app/itest/itest_lndharness_test.go:254 +0x44
github.com/bottlepay/lndsigner/itest_test.newTestContext(0xc000219380)
	/app/itest/itest_context_test.go:109 +0xae4
github.com/bottlepay/lndsigner/itest_test.TestIntegration(0x0?)
	/app/itest/lndsigner_test.go:31 +0x34
testing.tRunner(0xc000219380, 0xac05c8)
	/usr/local/go/src/testing/testing.go:1446 +0x18c
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1493 +0x568
FAIL	github.com/bottlepay/lndsigner/itest	600.050s
=== RUN   TestECDH
=== PAUSE TestECDH
=== RUN   TestSignMessage
=== PAUSE TestSignMessage
=== RUN   TestSignMessageSchnorr
=== PAUSE TestSignMessageSchnorr
=== RUN   TestSignPsbt
=== PAUSE TestSignPsbt
=== CONT  TestECDH
=== CONT  TestSignMessage
=== RUN   TestSignMessage/sign_single
=== CONT  TestSignMessageSchnorr
=== RUN   TestECDH/ecdh
=== RUN   TestSignMessageSchnorr/sign_single
=== RUN   TestECDH/vault_returned_no_shared_key
=== CONT  TestSignPsbt
=== RUN   TestECDH/vault_returned_bad_shared_key
=== RUN   TestSignPsbt/nil_PSBT
=== RUN   TestECDH/shared_key_not_hex
=== RUN   TestSignMessage/sign_double
=== RUN   TestECDH/error_on_request
=== RUN   TestSignMessageSchnorr/sign_double
=== RUN   TestSignMessage/sign_single_compact
=== RUN   TestSignPsbt/p2tr_spend
=== RUN   TestSignMessageSchnorr/sign_single_tweaked
=== RUN   TestSignMessageSchnorr/sign_double_tweaked
=== RUN   TestSignPsbt/p2wkh_spend
=== RUN   TestSignMessageSchnorr/error_on_request
--- PASS: TestECDH (0.00s)
    --- PASS: TestECDH/ecdh (0.00s)
    --- PASS: TestECDH/vault_returned_no_shared_key (0.00s)
    --- PASS: TestECDH/vault_returned_bad_shared_key (0.00s)
    --- PASS: TestECDH/shared_key_not_hex (0.00s)
    --- PASS: TestECDH/error_on_request (0.00s)
=== RUN   TestSignMessageSchnorr/vault_returned_no_signature
=== RUN   TestSignPsbt/np2wkh_spend
=== RUN   TestSignMessage/sign_double_compact
=== RUN   TestSignMessageSchnorr/signature_not_hex
=== RUN   TestSignMessageSchnorr/ErrSigTooShort
--- PASS: TestSignMessageSchnorr (0.00s)
    --- PASS: TestSignMessageSchnorr/sign_single (0.00s)
    --- PASS: TestSignMessageSchnorr/sign_double (0.00s)
    --- PASS: TestSignMessageSchnorr/sign_single_tweaked (0.00s)
    --- PASS: TestSignMessageSchnorr/sign_double_tweaked (0.00s)
    --- PASS: TestSignMessageSchnorr/error_on_request (0.00s)
    --- PASS: TestSignMessageSchnorr/vault_returned_no_signature (0.00s)
    --- PASS: TestSignMessageSchnorr/signature_not_hex (0.00s)
    --- PASS: TestSignMessageSchnorr/ErrSigTooShort (0.00s)
=== RUN   TestSignMessage/error_on_request
=== RUN   TestSignPsbt/ln1tweak_spend
=== RUN   TestSignMessage/vault_returned_no_signature
=== RUN   TestSignMessage/signature_not_hex
=== RUN   TestSignPsbt/vault_returned_no_pubkey
--- PASS: TestSignMessage (0.00s)
    --- PASS: TestSignMessage/sign_single (0.00s)
    --- PASS: TestSignMessage/sign_double (0.00s)
    --- PASS: TestSignMessage/sign_single_compact (0.00s)
    --- PASS: TestSignMessage/sign_double_compact (0.00s)
    --- PASS: TestSignMessage/error_on_request (0.00s)
    --- PASS: TestSignMessage/vault_returned_no_signature (0.00s)
    --- PASS: TestSignMessage/signature_not_hex (0.00s)
=== RUN   TestSignPsbt/pubkey_not_hex
=== RUN   TestSignPsbt/p2wkh_and_np2wkh_error_on_request
=== RUN   TestSignPsbt/np2wkh_and_p2wkh_vault_returned_no_signature
=== RUN   TestSignPsbt/np2wkh_and_p2wkh_signature_not_hex
=== RUN   TestSignPsbt/p2wkh_and_np2wkh_error_on_request#01
=== RUN   TestSignPsbt/p2tr_vault_returned_no_signature
=== RUN   TestSignPsbt/p2tr_signature_not_hex
--- PASS: TestSignPsbt (0.00s)
    --- PASS: TestSignPsbt/nil_PSBT (0.00s)
    --- PASS: TestSignPsbt/p2tr_spend (0.00s)
    --- PASS: TestSignPsbt/p2wkh_spend (0.00s)
    --- PASS: TestSignPsbt/np2wkh_spend (0.00s)
    --- PASS: TestSignPsbt/ln1tweak_spend (0.00s)
    --- PASS: TestSignPsbt/vault_returned_no_pubkey (0.00s)
    --- PASS: TestSignPsbt/pubkey_not_hex (0.00s)
    --- PASS: TestSignPsbt/p2wkh_and_np2wkh_error_on_request (0.00s)
    --- PASS: TestSignPsbt/np2wkh_and_p2wkh_vault_returned_no_signature (0.00s)
    --- PASS: TestSignPsbt/np2wkh_and_p2wkh_signature_not_hex (0.00s)
    --- PASS: TestSignPsbt/p2wkh_and_np2wkh_error_on_request#01 (0.00s)
    --- PASS: TestSignPsbt/p2tr_vault_returned_no_signature (0.00s)
    --- PASS: TestSignPsbt/p2tr_signature_not_hex (0.00s)
PASS
coverage: 72.4% of statements
ok  	github.com/bottlepay/lndsigner/keyring	0.063s	coverage: 72.4% of statements
?   	github.com/bottlepay/lndsigner/proto	[no test files]
=== RUN   TestECDH
=== PAUSE TestECDH
=== RUN   TestListNodes
=== PAUSE TestListNodes
=== RUN   TestDerivePubkey
=== PAUSE TestDerivePubkey
=== RUN   TestSign
=== PAUSE TestSign
=== RUN   TestImportNode
=== PAUSE TestImportNode
=== RUN   TestListAccounts
=== PAUSE TestListAccounts
=== CONT  TestListNodes
=== CONT  TestDerivePubkey
=== CONT  TestImportNode
=== CONT  TestListAccounts
=== CONT  TestSign
2023-02-08T07:30:04.135Z [ERROR] Failed to get seed from seed and pass phrases: error="seed phrase must be 24 words"
2023-02-08T07:30:04.135Z [ERROR] Failed to get seed from seed and pass phrases: error="seed phrase must use BIP39 word list"
2023-02-08T07:30:04.135Z [ERROR] Failed to get seed from seed and pass phrases: error="cipher seed version not recognized"
2023-02-08T07:30:04.135Z [ERROR] Failed to get seed from seed and pass phrases: error="checksum mismatch"
2023-02-08T07:30:04.308Z [INFO]  Wrote new LND seed: node=02429b0b76bad536ea38eac72f7b32935bd7ece3a64b7f030d2bb583ed65c8c12f
2023-02-08T07:30:04.308Z [INFO]  Wrote new LND seed: node=02277def656d38023aad3338ec68d5088afa512cb1c52a043df8e55e2edcd9ae4d
2023-02-08T07:30:04.308Z [INFO]  Wrote new LND seed: node=03c12148eb1758ddb4c5a589cfc08137a41b0926c9148661d7e4506bdfe03e11c6
2023-02-08T07:30:04.309Z [ERROR] Both single and double tweak specified
2023-02-08T07:30:04.314Z [ERROR] Failed to derive pubkey: node=02277def656d38023aad3338ec68d5088afa512cb1c52a043df8e55e2edcd9ae4d error="derivation path not 5 elements"
2023-02-08T07:30:04.314Z [ERROR] Failed to derive pubkey: node=02277def656d38023aad3338ec68d5088afa512cb1c52a043df8e55e2edcd9ae4d error="negative derivation path element"
2023-02-08T07:30:04.314Z [ERROR] Couldn't decode ln1tweak hex: error="encoding/hex: invalid byte: U+0067 'g'"
2023-02-08T07:30:04.314Z [ERROR] Failed to derive pubkey: node=02277def656d38023aad3338ec68d5088afa512cb1c52a043df8e55e2edcd9ae4d error="derivation path element > MaxUint32"
2023-02-08T07:30:04.314Z [ERROR] Failed to derive pubkey: node=02277def656d38023aad3338ec68d5088afa512cb1c52a043df8e55e2edcd9ae4d error="derivation path element not hardened"
--- PASS: TestDerivePubkey (0.18s)
=== CONT  TestECDH
2023-02-08T07:30:04.314Z [ERROR] Peer pubkey is wrong length: peer=abcdef
2023-02-08T07:30:04.315Z [ERROR] Failed to retrieve node info: node=abcdef error="invalid node id"
2023-02-08T07:30:04.315Z [ERROR] Failed to retrieve node info: node=02252bb0fdf7f6e7c055c5419c6fa1c9799cf348b480603b9c0af61dbdea29149e error="node not found"
2023-02-08T07:30:04.319Z [ERROR] Couldn't decode ln2tweak hex: error="encoding/hex: invalid byte: U+0067 'g'"
2023-02-08T07:30:04.320Z [INFO]  Wrote new LND seed: node=02533e4dc1544ccea4287e2e6b89b8c759372ab2e316836335810e51ea6175942f
2023-02-08T07:30:04.328Z [WARN]  Pubkey mismatch: node=02533e4dc1544ccea4287e2e6b89b8c759372ab2e316836335810e51ea6175942f error="pubkey mismatch"
2023-02-08T07:30:04.746Z [ERROR] Failed to get seed from seed and pass phrases: error="invalid passphrase"
2023-02-08T07:30:04.754Z [INFO]  Wrote new LND seed: node=03c7926302ac72f51ef009dc169561734414b3c6bfd9fb0dc42cac93101c3c25bf
2023-02-08T07:30:04.951Z [INFO]  Wrote new LND seed: node=023cf344b017a3c91bdb2c9c076da267555f0c0748099418ea1f558a624ced1ac6
2023-02-08T07:30:04.980Z [INFO]  Wrote new LND seed: node=03c7926302ac72f51ef009dc169561734414b3c6bfd9fb0dc42cac93101c3c25bf
2023-02-08T07:30:04.982Z [INFO]  Wrote new LND seed: node=023cf344b017a3c91bdb2c9c076da267555f0c0748099418ea1f558a624ced1ac6
--- PASS: TestECDH (0.68s)
--- PASS: TestSign (0.91s)
--- PASS: TestListAccounts (1.25s)
2023-02-08T07:30:05.499Z [ERROR] newNode: node pubkey mismatch
2023-02-08T07:30:05.652Z [INFO]  Wrote new LND seed: node=03c7926302ac72f51ef009dc169561734414b3c6bfd9fb0dc42cac93101c3c25bf
--- PASS: TestListNodes (1.52s)
2023-02-08T07:30:06.103Z [ERROR] Failed to parse network: error="invalid network" network=mainnet
2023-02-08T07:30:06.688Z [INFO]  Wrote new LND seed: node=023cf344b017a3c91bdb2c9c076da267555f0c0748099418ea1f558a624ced1ac6
2023-02-08T07:30:07.236Z [INFO]  Wrote new LND seed: node=03c7926302ac72f51ef009dc169561734414b3c6bfd9fb0dc42cac93101c3c25bf
2023-02-08T07:30:07.901Z [ERROR] newNode: node already exists: node=03c7926302ac72f51ef009dc169561734414b3c6bfd9fb0dc42cac93101c3c25bf
--- PASS: TestImportNode (3.77s)
PASS
coverage: 80.2% of statements
ok  	github.com/bottlepay/lndsigner/vault	3.956s	coverage: 80.2% of statements
FAIL
make: *** [Makefile:50: test-all] Error 1
make: *** [docker-test-all] Error 2
```

**Comment by aakselrod** [comment]
It looks like it's timing out waiting for bitcoind's `debug.log` which I'm guessing isn't working because I've specified amd64 as the platform. I need to set up platform detection in the Makefile and Dockerfile to be able to run the tests on ARM in a Docker container.

I'll test this out on a Raspberry Pi before submitting a PR for review.
